spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/impremkumar/spring-cloud-test
          search-paths:
            - '*'
      discovery:
        enabled: true
